version: 2.1

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t tgs-to-gif .
      - run: docker run --rm -e FORMAT=gif -v $(pwd)/stickers:/source tgs-to-gif
      - run: docker run --rm -e FORMAT=webp -v $(pwd)/stickers:/source tgs-to-gif
